#ifndef __DT_BINDINGS_RZA1_DMA_H__
#define __DT_BINDINGS_RZA1_DMA_H__

#define RZA1DMA_SLAVE_PCM_MEM_SSI0	1	/* DMA0		MEM->(DMA0)->SSI0 */
#define RZA1DMA_SLAVE_PCM_MEM_SRC1	2	/* DMA1		MEM->(DMA1)->FFD0_1->SRC1->SSI0 */
#define RZA1DMA_SLAVE_PCM_SSI0_MEM	3	/* DMA2		SSI0->(DMA2)->MEM */
#define RZA1DMA_SLAVE_PCM_SRC0_MEM	4	/* DMA3		SSI0->SRC0->FFU0_0->(DMA3)->MEM */
#define RZA1DMA_SLAVE_PCM_MAX 		5
#define RZA1DMA_SLAVE_SDHI0_TX		6
#define RZA1DMA_SLAVE_SDHI0_RX		7
#define RZA1DMA_SLAVE_SDHI1_TX		8
#define RZA1DMA_SLAVE_SDHI1_RX		9
#define RZA1DMA_SLAVE_MMCIF_TX		10
#define RZA1DMA_SLAVE_MMCIF_RX		11

#define RZA1DMA_SLAVE_SPI0_TX		12
#define RZA1DMA_SLAVE_SPI0_RX		13
#define RZA1DMA_SLAVE_SPI2_TX		14
#define RZA1DMA_SLAVE_SPI2_RX		15

#endif /* __DT_BINDINGS_RZA1_DMA_H__ */
