# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-y += clk-mstar-cpupll.o \
	 clk-mstar-pll-gater.o \
	 clk-mstar-mux.o \
	 clk-mstar-upll.o \
	 clk-mstar_lpll.o \
	 clk-mstar_clkgen-gates.o \
	 clk-mstar_miupll.o \
	 clk-mstar-mpll.o \
	 clk-mstar-pll_common.o
